# Generated by Django 4.1.1 on 2022-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockstatus',
            name='in_stock_status',
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock')], default='IN STOCK', max_length=15, null=True),
        ),
    ]
