# Generated by Django 4.1.1 on 2022-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title_eng',
            field=models.CharField(db_index=True, help_text="The book's name in English.", max_length=200, null=True),
        ),
    ]
