# Generated by Django 4.1.1 on 2022-10-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_remove_stockstatus_in_stock_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageslightnovel',
            name='language_lightnovel',
        ),
        migrations.AddField(
            model_name='languageslightnovel',
            name='language_lightnovel_select',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('JAPANESE', 'Japanese')], default='ENGLISH', max_length=10),
        ),
        migrations.AddField(
            model_name='lightnovel',
            name='volume_no',
            field=models.CharField(blank=True, help_text="The volume's number of the lightnovel.", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='lightnovelcategory',
            name='lightnovel_tag_label',
            field=models.CharField(blank=True, help_text='For the lightnovel short detail.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_title',
            field=models.CharField(blank=True, help_text="The artist's title.", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_title',
            field=models.CharField(blank=True, help_text='The title of the author.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='Lightnovel_description',
            field=models.TextField(blank=True, help_text="For the lightnovel's description.", null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='The artist of the lightnovel.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.artist'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='The contributor of the lightnovel.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.contributor'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='', verbose_name='/image'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='isbn_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='ISBN numbers of the book.'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='language_lightnovel',
            field=models.ForeignKey(help_text='The language of the lightnovel.', on_delete=django.db.models.deletion.CASCADE, to='store_app.languageslightnovel'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='lightnovel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.lightnovelcategory'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='lightnovel_title_eng',
            field=models.CharField(blank=True, db_index=True, help_text='The title of the book in english.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='lightnovel_title_jp',
            field=models.CharField(blank=True, db_index=True, help_text='The title of the book in japanese.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='pages',
            field=models.CharField(blank=True, help_text="The book's page.", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.publisher'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='stock_volume',
            field=models.IntegerField(blank=True, help_text='The stock of the lightnovel in the warehouse.', null=True),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='year',
            field=models.CharField(blank=True, help_text='The first year of lightnovel that was published.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, help_text="The publisher's email.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(blank=True, help_text='The name of the publisher.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, help_text="The publisher's website.", null=True),
        ),
    ]
