# Generated by Django 4.1.1 on 2022-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_book_book_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
