# Generated by Django 4.1.1 on 2022-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_remove_languageslightnovel_language_lightnovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='', verbose_name='meadia/store_app/image'),
        ),
    ]
