# Generated by Django 4.1.1 on 2022-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_lightnovel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='', verbose_name='media/store_app/image'),
        ),
    ]
