# Generated by Django 4.1.1 on 2022-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_lightnovel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='store_app/images'),
        ),
    ]
