# Generated by Django 4.1.1 on 2022-10-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_lightnovel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightnovel',
            old_name='lightnovel_title_eng',
            new_name='book_title_eng',
        ),
        migrations.RenameField(
            model_name='lightnovel',
            old_name='lightnovel_title_jp',
            new_name='book_title_jp',
        ),
        migrations.RenameField(
            model_name='lightnovel',
            old_name='isbn_number',
            new_name='isbn',
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='', verbose_name='media/store_app/image'),
        ),
    ]
