# Generated by Django 4.1.1 on 2022-10-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_rename_lightnovel_title_eng_lightnovel_book_title_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(blank=True, help_text="The publisher's name.", max_length=20, null=True),
        ),
    ]
