# Generated by Django 4.1.1 on 2022-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_publisher_publisher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contributor_title',
            field=models.CharField(blank=True, help_text="The contributor's name.", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(blank=True, help_text="The publisher's name.", max_length=30, null=True),
        ),
    ]
