# Generated by Django 4.1.1 on 2022-10-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_contributor_contributor_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_language_select', models.CharField(choices=[('ENGLISH', 'English'), ('JAPANESE', 'Japanese')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lightnovel',
            name='language_lightnovel',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_title',
            field=models.CharField(blank=True, help_text="The artist's name.", max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='LanguagesLightnovel',
        ),
        migrations.AddField(
            model_name='lightnovel',
            name='book_language',
            field=models.ForeignKey(blank=True, help_text="The book's language", null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.booklanguage'),
        ),
    ]
