# Generated by Django 4.1.1 on 2022-10-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_bookcategory_remove_lightnovel_lightnovel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightnovel',
            old_name='book_category',
            new_name='book_category_1st',
        ),
        migrations.RemoveField(
            model_name='lightnovel',
            name='Lightnovel_description',
        ),
    ]
