# Generated by Django 4.1.1 on 2022-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_rename_book_category_lightnovel_book_category_1st_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcategory',
            old_name='book_category_tag',
            new_name='book_category_tag_1s',
        ),
        migrations.RenameField(
            model_name='lightnovel',
            old_name='book_category_1st',
            new_name='book_categories',
        ),
    ]
