# Generated by Django 4.1.1 on 2022-10-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_rename_book_category_tag_1s_bookcategory_book_category_tag_1st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='book_category_tag_label',
            field=models.CharField(blank=True, help_text="The book(lightnovel)'s tage label.", max_length=200, null=True),
        ),
    ]
