# Generated by Django 4.1.1 on 2022-10-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_bookcategory_book_category_tag_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title_eng', models.CharField(blank=True, db_index=True, help_text="The book's name in English.", max_length=200, null=True)),
                ('book_title_jp', models.CharField(blank=True, db_index=True, help_text="The book's name in Japanese(Romaji).", max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='ISBN numbers of the book.')),
                ('year', models.CharField(blank=True, help_text='The first year of (book)lightnovel that was published.', max_length=4, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('pages', models.CharField(blank=True, help_text="The book(lightnovel)'s page.", max_length=4, null=True)),
                ('image', models.ImageField(blank=True, help_text='For the image.', null=True, upload_to='', verbose_name='/store_app/image')),
                ('volume_no', models.CharField(blank=True, help_text="The volume's number of the (book)lightnovel.", max_length=3, null=True)),
                ('stock_volume', models.IntegerField(blank=True, help_text='The stock of the (book)lightnovel in the warehouse.', null=True)),
                ('datetime_create', models.DateTimeField()),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, help_text='The premium price of the lightnovel.', max_digits=6, null=True)),
                ('normal_price', models.DecimalField(blank=True, decimal_places=2, help_text='The normal price of the lightnovel.', max_digits=6, null=True)),
                ('artist', models.ForeignKey(blank=True, help_text='The artist of the book(lightnovel).', null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.artist')),
                ('book_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.bookcategory')),
                ('book_language', models.ForeignKey(blank=True, help_text="The book's language", null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.booklanguage')),
                ('contributor', models.ForeignKey(blank=True, help_text='The contributor of the book(lightnovel).', null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.contributor')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.publisher')),
                ('stock_status_now', models.ForeignKey(help_text='The status of the stock.', on_delete=django.db.models.deletion.CASCADE, to='store_app.stockstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='Lightnovel',
        ),
    ]
