# Generated by Django 4.1.1 on 2022-10-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_book_delete_lightnovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, help_text='The description that describe the book.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.ForeignKey(blank=True, help_text="The book(lightnovel)'s language", null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.booklanguage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text="For the book(lightnovel)'s image.", null=True, upload_to='', verbose_name='/store_app/image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='normal_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The normal price of the (book)lightnovel.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The premium price of the (book)lightnovel.', max_digits=6, null=True),
        ),
    ]
