# Generated by Django 4.1.1 on 2022-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_book_book_description_alter_book_book_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeriesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
