# Generated by Django 4.1.1 on 2022-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_person_last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_perpose_message', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_message_detail', models.TextField(blank=True, null=True)),
                ('time_contact_message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
