# Generated by Django 4.1.1 on 2022-11-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_person_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_person_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_person_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_perpose_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_message_detail',
            new_name='message_detail',
        ),
    ]
