# Generated by Django 4.1.1 on 2022-10-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message_detail',
            new_name='contact_message_detail',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='perpose_message',
            new_name='contact_perpose_message',
        ),
    ]
