# Generated by Django 4.1.1 on 2022-10-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_rename_message_detail_contactmessage_contact_message_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='time_contact_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
