# Generated by Django 4.1.1 on 2022-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_alter_contactmessage_time_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_message_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_perpose_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_person_first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_person_last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
